default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: just_cook_it_development

test:
  <<: *default
  database: just_cook_it_test

production:
  <<: *default
  database: just_cook_it_production
  password: <%= ENV['JUSTCOOKIT_DATABASE_PASSWORD'] %>
